# Generated by Django 3.2.6 on 2021-09-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
