# Generated by Django 3.2.6 on 2021-09-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe_app', '0003_auto_20210919_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='logo_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='logo_image',
        ),
        migrations.AddField(
            model_name='footer',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
