# Generated by Django 3.2.6 on 2021-09-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe_app', '0005_myuser_workimagemodel_workmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
