# Generated by Django 3.2.6 on 2021-09-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe_app', '0006_delete_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarmodel',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
