# Generated by Django 3.2.6 on 2021-09-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe_app', '0008_workmodel_work_head_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(blank=True, max_length=100, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='about_image')),
            ],
        ),
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('about_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
