# Generated by Django 3.2.6 on 2021-09-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe_app', '0009_aboutimagemodel_aboutmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
