# Generated by Django 3.2.6 on 2021-09-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe_app', '0010_workssectionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='work_foot_image',
            field=models.ImageField(blank=True, null=True, upload_to='work_image'),
        ),
    ]
