# Generated by Django 3.2.6 on 2021-09-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe_app', '0011_workmodel_work_foot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workimagemodel',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
