# Generated by Django 3.2.6 on 2021-09-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe_app', '0012_workimagemodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
