# Generated by Django 3.2.6 on 2021-09-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe_app', '0014_contactaddressmodel_contactsocnetmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsocnetmodel',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
