# Generated by Django 3.2.6 on 2021-09-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe_app', '0015_contactsocnetmodel_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsocnetmodel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='contact_image'),
        ),
    ]
