# Generated by Django 3.2.6 on 2021-09-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe_app', '0016_alter_contactsocnetmodel_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarGuestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
