# Generated by Django 3.2.6 on 2021-09-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe_app', '0017_navbarguestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
